name: Update Plugin Versions

on:
  # Runs once a day at midnight; adjust as you prefer
  schedule:
    - cron: '0 0 * * *'
  # Also allows manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Fetch versions and update README
        run: |
          python scripts/fetch_versions.py

      - name: Run fetch_versions.py
        run: |
          python scripts/fetch_versions.py
          echo "---- README AFTER SCRIPT ----"
          cat README.md
          echo "---- GIT DIFF ----"
          git diff README.md
          echo "---- END GIT DIFF ----"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet || git commit -m "chore: Update plugin & game versions"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          branch: main
