name: Update Plugin Versions

on:
  # Schedule daily at midnight (UTC). Adjust as desired.
  schedule:
    - cron: '0 0 * * *'
  # Allows manual trigger from the GitHub Actions tab.
  workflow_dispatch:
permissions:
  contents: write

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch plugin versions & update README
        run: |
          python scripts/fetch_versions.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # Only commit if there are actual changes
          git diff --quiet || git commit -m "chore: Update plugin versions"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          branch: main
  	  repository: "TerraNova-Devs/.github"
